apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: pedinephro
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "<BASE64_USERNAME_PASSWORD>"
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: pedinephro
stringData:
  mysql-password: "root"
  keycloak-client-secret: "your_keycloak_secret"
