apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: pedinephro

data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hospitalisation
  SPRING_DATASOURCE_USERNAME: root
  EUREKA_SERVER: http://eureka:8761/eureka/

  twilio.account.sid: "test"
  twilio.auth.token: "test"
  twilio.phone.number: "+10000000000"
