apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: pedinephro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: azizos07/user-service:latest
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/pedinephro"
        - name: SPRING_DATASOURCE_USERNAME
          value: "pedinephro"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mysql-password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: EUREKA_SERVER
        - name: KEYCLOAK_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KEYCLOAK_SERVER_URL
        - name: KEYCLOAK_REALM
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KEYCLOAK_REALM
        - name: SERVER_PORT
          value: "8081"
        ports:
        - containerPort: 8081
        startupProbe:
          tcpSocket:
            port: 8081
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: pedinephro
spec:
  selector:
    app: user-service
  ports:
  - port: 8081
    targetPort: 8081